<?php
/*
 * Pfarrplaner
 *
 * @package Pfarrplaner
 * @author Christoph Fischer <chris@toph.de>
 * @copyright (c) 2020 Christoph Fischer, https://christoph-fischer.org
 * @license https://www.gnu.org/licenses/gpl-3.0.txt GPL 3.0 or later
 * @link https://github.com/pfarrplaner/pfarrplaner
 * @version git: $Id$
 *
 * Sponsored by: Evangelischer Kirchenbezirk Balingen, https://www.kirchenbezirk-balingen.de
 *
 * Pfarrplaner is based on the Laravel framework (https://laravel.com).
 * This file may contain code created by Laravel's scaffolding functions.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace App\HomeScreen\Tabs;


use App\Baptism;
use App\Funeral;
use App\Service;
use App\Wedding;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class CasesHomeScreenTab extends AbstractHomeScreenTab
{

    protected $title = 'Kasualien';
    protected $description = 'Zeigt die Kasualienplanung für eine Auswahl von Gemeinden';

    protected $queries = [];

    public function __construct($config = [])
    {
        $this->setDefaultConfig($config, ['includeCities' => [], 'title' => 'Kasualien']);
        parent::__construct($config);
        $this->buildQueries();
    }

    public function getTitle(): string
    {
        return $this->config['title'] ?: $this->title;
    }

    public function getContent($data = [])
    {
        foreach (['funerals', 'weddings', 'baptisms'] as $item) {
            $data[$item] = $this->queries[$item]->get();
        }
        return parent::getContent($data);
    }

    public function toArray($data = [])
    {
        foreach (['funerals', 'weddings', 'baptisms'] as $item) {
            $data[$item] = $this->queries[$item]->get();
            $data[$item.'Count'] = count($data[$item]);
        }
        return parent::toArray($data); // TODO: Change the autogenerated stub
    }


    protected function buildQueries()
    {
        $cities = (is_array($this->config['includeCities']) ? $this->config['includeCities'] : [$this->config['includeCities']]);

        $this->queries['funerals'] = Funeral::with(['service', 'service.day'])
            ->select(['funerals.*'])
            ->join('services', 'services.id', 'funerals.service_id')
            ->join('days', 'days.id', 'services.day_id')
            ->whereHas('service', function($service) use ($cities){
                $service->whereIn('city_id', $cities);
            })->orderBy('days.date', 'DESC')
            ->orderBy('time', 'DESC')
            ->limit(10);

        $this->queries['weddings'] = Wedding::with(['service', 'service.day'])
            ->select(['weddings.*', 'services.*'])
            ->join('services', 'services.id', 'weddings.service_id')
            ->join('days', 'days.id', 'services.day_id')
            ->whereHas('service', function($service) use ($cities){
                $service->whereIn('city_id', $cities);
            })->orderBy('days.date', 'DESC')
            ->orderBy('time', 'DESC')
            ->limit(10);

        $this->queries['baptisms'] = Baptism::with(['service', 'service.day'])
            ->select(['baptisms.*', 'services.*'])
            ->join('services', 'services.id', 'baptisms.service_id')
            ->join('days', 'days.id', 'services.day_id')
            ->whereHas('service', function($service) use ($cities){
                $service->whereIn('city_id', $cities);
            })->orderBy('days.date', 'DESC')
            ->orderBy('time', 'DESC')
            ->limit(10);

    }

}
